# Generated by Django 3.2.8 on 2023-12-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tagCompletion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tagTeaser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
