# Generated by Django 3.2.8 on 2023-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231209_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageHeroDesktop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imageHeroMobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
