# Generated by Django 3.2.8 on 2023-12-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231212_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imageHeight',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageWidth',
        ),
        migrations.AddField(
            model_name='blog',
            name='imageHeightDesktop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imageHeightMobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imageWidthDesktop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imageWidthMobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
