# Generated by Django 3.2.8 on 2023-12-13 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_auto_20231212_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('goLive', models.CharField(blank=True, max_length=200, null=True)),
                ('podcastTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('imageThumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('imageHeroMobile', models.CharField(blank=True, max_length=200, null=True)),
                ('imageHeroDesktop', models.CharField(blank=True, max_length=200, null=True)),
                ('imageWidthMobile', models.IntegerField(blank=True, default=0, null=True)),
                ('imageHeightMobile', models.IntegerField(blank=True, default=0, null=True)),
                ('imageWidthDesktop', models.IntegerField(blank=True, default=0, null=True)),
                ('imageHeightDesktop', models.IntegerField(blank=True, default=0, null=True)),
                ('imageRef1', models.CharField(blank=True, max_length=200, null=True)),
                ('imageRef2', models.CharField(blank=True, max_length=200, null=True)),
                ('imageRef3', models.CharField(blank=True, max_length=200, null=True)),
                ('minuteRead', models.IntegerField(blank=True, default=0, null=True)),
                ('tagTeaser', models.CharField(blank=True, max_length=200, null=True)),
                ('tagCompletion', models.CharField(blank=True, max_length=200, null=True)),
                ('subTitle1', models.CharField(blank=True, max_length=200, null=True)),
                ('subTitle2', models.CharField(blank=True, max_length=200, null=True)),
                ('caption1', models.CharField(blank=True, max_length=200, null=True)),
                ('caption2', models.CharField(blank=True, max_length=200, null=True)),
                ('captchaPhrase', models.TextField(blank=True, null=True)),
                ('callToAction1', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
