# Generated by Django 3.2.8 on 2023-12-13 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_podcasts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcasts',
            new_name='Podcast',
        ),
    ]
