# Generated by Django 3.2.8 on 2023-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20231214_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogTitle',
            new_name='blogTitleFrontend',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogTitleBackend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
