# Generated by Django 3.2.8 on 2024-02-22 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_auto_20231218_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('goLive', models.CharField(blank=True, max_length=200, null=True)),
                ('podcastTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('imageThumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('imageHeroMobile', models.CharField(blank=True, max_length=200, null=True)),
                ('minuteRead', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='callToAction1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='callToAction2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='callToAction3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='captchaPhrase1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='captchaPhrase2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='caption1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description10',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description11',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description12',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description13',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description14',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description15',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description6',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description7',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description8',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description9',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageHeightDesktop',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageHeightMobile',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageHeroDesktop',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageRef1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageRef2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageRef3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageWidthDesktop',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imageWidthMobile',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='orderList1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='orderList2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='orderList3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='orderList4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='orderList5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subTitle1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subTitle2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subTitle3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subTitle4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tagCompletion',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tagTeaser',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
