# Generated by Django 3.2.8 on 2024-02-24 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20240222_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('goLive', models.CharField(blank=True, max_length=200, null=True)),
                ('contentTitleFrontend', models.CharField(blank=True, max_length=200, null=True)),
                ('contentTitleBackend', models.CharField(blank=True, max_length=200, null=True)),
                ('imageThumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('contentTag', models.CharField(blank=True, max_length=200, null=True)),
                ('minuteRead', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
