# Generated by Django 3.2.8 on 2024-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20240224_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
